name = "Lecture FOOBAR"
conferenceurl = "https://meet.jit.si/"
backlogminutes = 20
# Do users have to exist in db, or do we accept any usernames (with any password)
acceptanyusers = false

[[timeslots]]
day   = "Monday"
start = "08:15"
end   = "18:45"

[[authdb]]
user  = 'user1'
pass  = 'pw'
admin = false
uinfo = 'Text <a href="#this">Link</a>!'
url = 'https://meet.jit.si/user1'

[[authdb]]
user  = 'user2'
pass  = 'pw'
admin = false
uinfo = 'Text2!'
url = 'https://meet.jit.si/user2'

[[authdb]]
user  = 'admin1'
pass  = 'admin'
admin = true
uinfo = 'Text Admin'
url = 'https://meet.jit.si/admin1'
