name = "Lecture FOOBAR"

[[timeslots]]
day   = "Thursday"
start = "10:15"
end   = "18:45"

[[authdb]]
user  = 'user1'
pass  = 'pw'
admin = false

[[authdb]]
user  = 'user2'
pass  = 'pw'
admin = false

[[authdb]]
user  = 'user3'
pass  = 'pw'
admin = false

[[authdb]]
user  = 'user4'
pass  = 'pw'
admin = false

[[authdb]]
user  = 'user5'
pass  = 'pw'
admin = false

[[authdb]]
user  = 'user6'
pass  = 'pw'
admin = false

[[authdb]]
user  = 'user7'
pass  = 'pw'
admin = false

[[authdb]]
user  = 'user8'
pass  = 'pw'
admin = false

[[authdb]]
user  = 'admin1'
pass  = 'admin'
admin = true

[[authdb]]
user  = 'admin2'
pass  = 'admin'
admin = true

[[authdb]]
user  = 'admin3'
pass  = 'admin'
admin = true

[[authdb]]
user  = 'admin4'
pass  = 'admin'
admin = true

[[authdb]]
user  = 'admin5'
pass  = 'admin'
admin = true
