name: adora-belle
license: "AGPL-3"
description: Dispatcher for the webrtc-golem-trust

ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - adora-belle
      - servant-client
      - warp >= 3.2.4
      - http-client
      - http-types

library:
  source-dirs:
    - src

executables:
  adora-belle:
    main: exe/Main.hs
    dependencies:
      - adora-belle
    ghc-options:
      - -threaded
      - -rtsopts

dependencies:
  - base
  - servant
  - servant-server
  - transformers
  - aeson
  - wai
  - warp
  - wai-logger
  - uuid
  - time
  - random
  - containers
  - bytestring
  - stm
  - utf8-string
  - servant-auth
  - servant-foreign
  - text
  - htoml
  - optparse-applicative
  - filepath
  - parsec
  - either
  - bcrypt
